model:
  base_learning_rate: 4.5e-6
  target: stage1.models.autoencoder.VAENoDiscModel
  params:
    embed_dim: 4
    input_key: 'weight'
    learning_rate: 1.115e-4
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
#        kl_weight: 0.01
        kl_weight: 0.000001
    ddconfig:
      double_z: True
      tanh_out: False
      z_channels: 4
      resolution: 256
      in_channels: 32
      my_channels: 64
      out_ch: 32
      ch: 128
      ch_mult: [ 1,1,1, 2 ]  #num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ 8 ]
      dropout: 0.0
      in_dim: 16384
      fdim: 16384

data:
  target: zooloaders.autoloader.ZooDataModule
  params:
    data_dir: '../../Datasets/'
    batch_size: 32
    num_workers: 16
    scale: 0.1
    topk: null
    normalize: False
