model:
  base_learning_rate: 4.5e-6
  target: stage1.models.convmodels.VAENoDiscModel
  params:
#    monitor: "val/rec_loss"
    embed_dim: 4 #128 #64
    input_key: 'weight'
    learning_rate: 1.115e-3
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
#        kl_weight: 0.01
        kl_weight: 0.000001
    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 512
      in_channels: 224
      out_ch: 224
      ch: 64
      ch_mult: [ 1,1,1,2]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [4]
      dropout: 0.0
