model:
  base_learning_rate: 4.5e-4
  target: stage1.models.autoencoder.VAENoDiscModel
  params:
    embed_dim: 4
    input_key: 'weight'
    learning_rate: 1.51115e-4
#    ckpt_path: 'checkpoints/stage1/attn_first_stage_31_VAGOsolutions_.pt'
#    ckpt_path: 'checkpoints/stage1/attn_first_stage_llama3_3_8b_instruct.pt'
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
        #        kl_weight: 0.01
        kl_weight: 0.000001
    ddconfig:
      double_z: True
      tanh_out: True
      z_channels: 4
      resolution: 128
      in_channels: 16
      my_channels: 32
      out_ch: 16
      ch: 128
      ch_mult: [ 1,1, 1,2 ]  #num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ 8 ]
      dropout: 0.0
      in_dim: 5923
      fdim: 8192

data:
  target: zooloaders.autoloader.ZooDataModule
  params:
    data_dir: '../Datasets/'
    batch_size: 20
    num_workers: 4
    scale: 10
    topk: null
    normalize: False
