model:
  base_learning_rate: 4.5e-6
  target: stage1.models.first_stage_model.VAENoDiscModel
  params:
    embed_dim: 64
    input_key: 'weight'
    learning_rate: 2.115e-5
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
#        kl_weight: 0.01
        kl_weight: 0.000001
    ddconfig:
      double_z: True
      tanh_out: False
      z_channels: 64
      resolution: 64
      in_channels: 331
      my_channels: 331
      out_ch: 331
      ch: 256
      ch_mult: [ 1,1, 4, 4]  # num_down = len(ch_mult)-1
      num_res_blocks: 3
      attn_resolutions: [2, 4, 8]
      dropout: 0.1
      in_dim: 5923
      fdim: 4096

data:
  target: zooloaders.autoloader.ZooDataModule
  params:
    data_dir: '../../Datasets/llama3_weights'
    batch_size: 32
    num_workers: 8
    scale: 0.0125
    topk: null
    normalize: False
