model:
  base_learning_rate: 4.5e-6
  target: stage1.models.clipmodel.VAENoDiscModel
  params:
    embed_dim: 4 #4
    learning_rate: 1.3333e-3
    input_key: "weight"
    cond_key: "dataset"
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
        kl_weight: 1e-6
    ddconfig:
      double_z: True
      z_channels: 4
      z_ch: 4
      z_size: 16
      ch: 3
      in_channels: 3
      z_dim: 512



#clip_encoder_config_kl.yaml