model:
  base_learning_rate: 4.5e-4
  target: stage1.models.first_stage_model.VAENoDiscModel
  params:
    embed_dim: 4
    input_key: 'weight'
    learning_rate: 1.1234e-4
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
#        kl_weight: 0.01
        kl_weight: 1e-6
    ddconfig:
      clip_model_name: "ViT-B/32"
      latent_dim: 1024
      double_z: True
      tanh_out: False
      z_channels: 4
      resolution: 224
      in_channels: 4
      out_ch: 4
      ch: 128
      ch_mult: [ 1, 1, 1, 2 ]
      num_res_blocks: 2
      attn_resolutions: [28]
      dropout: 0.0
#      resamp_with_conv: True



# decoder_kwargs = {
#                'clip_model_name': "ViT-B/32",
#                "latent_dim": 1024,
#                "input_channel": 4,
#                'out_channels': 4,
#                "ch": 64,
#                "ch_mult": (1, 2, 4, 2),
#                "num_res_blocks": 2,
#                "attn_resolutions": (28,),  # adjust as needed
#                "dropout": 0.0,
#                "resamp_with_conv": True,
#                "resolution": 224,
#                "z_channels": 16,
#                "give_pre_end": False,
#                "tanh_out": False,
#                "use_linear_attn": False,
#                "attn_type": "vanilla"
#            }


data:
  target: zooloaders.autoloader.ZooDataModule
  params:
    data_dir: '../../Datasets/'
    batch_size: 16
    num_workers: 4
    scale: 0.1
    topk: null
    normalize: False
