model:
  base_learning_rate: 4.5e-6
  target: stage1.models.first_stage_c1model.VAENoDiscModel
  params:
#    monitor: "val/rec_loss"
    embed_dim: 16 #128 #64
    input_key: 'weight'
    learning_rate: 1.125e-4
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
#        kl_weight: 0.01
        kl_weight: 1e-6
    ddconfig:
      double_z: True
      tanh_out: False
      z_channels: 16
      resolution: 128
      in_channels: 128
      in_ch: 1
      out_ch: 128
      ch: 128
      ch_mult: [ 1,1,2, 2]  # num_down = len(ch_mult)-1
      num_res_blocks: 3
      attn_resolutions: [4, 8]
      dropout: 0.0
      in_dim: 16384
      fdim: 16384