model:
  base_learning_rate: 4.5e-6
  target: stage1.models.first_stage_c1model.VAENoDiscModel
  params:
#    monitor: "val/rec_loss"
    embed_dim: 4 #128 #64
    input_key: 'weight'
    learning_rate: 1.115e-5
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
#        kl_weight: 0.01
        kl_weight: 1.0
    ddconfig:
      double_z: True
      tanh_out: True
      z_channels: 4
      resolution: 8192
      in_channels: 128
      in_ch: 128
      out_ch: 128
      ch: 128
      ch_mult: [ 1,1,2, 2]  # num_down = len(ch_mult)-1
      num_res_blocks: 1
      attn_resolutions: [4, 8]
      dropout: 0.0
      in_dim: 8192
      fdim: 8192