model:
  base_learning_rate: 4.5e-6
  target: stage1.models.first_stage_model.VAENoDiscModel
  params:
#    monitor: "val/rec_loss"
    embed_dim: 4 #128 #64
    input_key: 'weight'
    learning_rate: 1.113e-3
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
#        kl_weight: 0.01
        kl_weight: 0.000001
    ddconfig:
      double_z: False
      z_channels: 4
      resolution: 128
      in_ch: 4096
      my_channels: 256
      out_ch: 16
      ch: 128
      num_res_blocks: 2
      attn_resolutions: [ 8, 4 ]
      dropout: 0.0
      in_dim: 12288
      fdim: 4096
      flat: True

