model:
  base_learning_rate: 4.5e-6
  target: stage1.models.first_stage_c1model.VAENoDiscModel
  params:
#    monitor: "val/rec_loss"
    embed_dim: 4 #128 #64
    input_key: 'weight'
    learning_rate: 1.115e-4
    lossconfig:
      target: stage1.modules.losses.CustomLosses.NopaddingLoss
      params:
#        kl_weight: 0.01
        kl_weight: 0.000001
    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 2048
      in_channels: 2048
      in_ch: 2048
      out_ch: 2048
      ch: 128
      ch_mult: [ 1,1,1,1]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [512, 1024]
      dropout: 0.0
      in_dim: 2048
      fdim: 2048