model:
  base_learning_rate: 4.5e-6
  target: stage1.models.simplemodel.VAENoDiscModel
  params:
    embed_dim: 4 #4
    learning_rate: 1.3333e-3
    input_key: "weight"
    cond_key: "dataset"
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
        kl_weight: 1e-6
    ddconfig:
      double_z: True
      z_channels: 16
      input_size: 512
      in_channels: 512
      my_channels: 4096
      in_dim: 14336
      fdim: 8192


