model:
  base_learning_rate: 4.5e-6
  target: stage1.models.first_stage_model.VAENoDiscModel
  params:
    embed_dim: 4
    input_key: 'weight'
    learning_rate: 1.115e-4
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
#        kl_weight: 0.01
        kl_weight: 0.000001
    ddconfig:
      double_z: True
      tanh_out: False
      z_channels: 4
      resolution: 128
      in_channels: 16
      my_channels: 32
      out_ch: 16
      ch: 256
      ch_mult: [ 1,1, 4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ 2, 4 ]
      dropout: 0.0
      in_dim: 5923
      fdim: 8192

data:
  target: zooloaders.autoloader.ZooDataModule
  params:
    data_dir: '../../Datasets/llama3_weights'
    batch_size: 32
    num_workers: 8
    scale: 0.0125
    topk: null
    normalize: False
