model:
  base_learning_rate: 4.5e-4
  target: stage1.models.conv_models.VAENoDiscModel
  params:
    embed_dim: 4
    input_key: 'weight'
    learning_rate: 1.234e-4
#    ckpt_path: 'checkpoints/stage1/img_base_chunk_llama_v1.ckpt'
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
#        kl_weight: 0.01
        kl_weight: 1e-6
    ddconfig:
      double_z: True
      tanh_out: False
      z_channels: 4
      resolution: 256
      in_channels: 1
      my_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [ 1,1, 1, 4]  #num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ 8 ]
      dropout: 0.0
      in_dim: 16384
      fdim: 16384


data:
  target: zooloaders.autoloader.ZooDataModule
  params:
    data_dir: '../../Datasets/'
    batch_size: 16
    num_workers: 4
    scale: 0.1
    topk: null
    normalize: False
