model:
  base_learning_rate: 4.5e-6
  target: stage1.models.simplemodel.VAENoDiscModel
  params:
    embed_dim: 4 #4
    learning_rate: 1.113e-3
    input_key: "weight"
    cond_key: "dataset"
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
        kl_weight: 1e-6
    ddconfig:
      double_z: True
      z_channels: 4
      input_size: 128
      in_channels: 13
      my_channels: 13
      in_dim: 20480
      fdim: 16384