model:
  base_learning_rate: 4.5e-6
  target: stage1.models.linear_autoencoder.VAENoDiscModel
  params:
    embed_dim: 1024 #4
    learning_rate: 1.113e-3
    input_key: "weight"
    cond_key: "dataset"
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
        kl_weight: 1e-6
    ddconfig:
      double_z: True
      z_features: 32
      in_channels: 16
      in_dim: 12288
      fdim: 12288

