model:
  base_learning_rate: 4.5e-4
  target: stage1.models.first_stage_model.VAENoDiscModel
  params:
    embed_dim: 4
    input_key: 'weight'
    learning_rate: 1.12315e-4
#    ckpt_path: 'checkpoints/stage1/attn_first_stage_31_VAGOsolutions_.pt'
#    ckpt_path: 'checkpoints/stage1/attn_first_stage_llama3_3_8b_instruct.pt'
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
        #        kl_weight: 0.01
        kl_weight: 0.000001
    ddconfig:
      double_z: True
      tanh_out: True
      z_channels: 4
      resolution: 64
      in_channels: 331
      my_channels: 331
      out_ch: 331
      ch: 128
      ch_mult: [ 1,4, 4]  #num_down = len(ch_mult)-1
      num_res_blocks: 3
      attn_resolutions: [ 8 ]
      dropout: 0.0
      in_dim: 5923
      fdim: 4096

data:
  target: zooloaders.autoloader.ZooDataModule
  params:
    data_dir: '../../Datasets/'
    batch_size: 16
    num_workers: 4
    scale: 0.1
    topk: null
    normalize: False
