model:
  base_learning_rate: 4.5e-4
  target: stage1.models.Denseencoder.VAENoDiscModel
  params:
    embed_dim: 256
    input_key: 'weight'
    learning_rate: 4.123e-5
#    ckpt_path: 'checkpoints/stage1/base_small_chunk_llama_.ckpt'
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
#        kl_weight: 0.01
        kl_weight: 0.00001
    ddconfig:
      double_z: True
      z_features: 256
      in_channels: 1
      my_channels: 1
      mult: [ 1,1,2]  #num_down = len(ch_mult)-1
      num_residual_blocks: 1
      in_dim: 4096
      fdim: 2048



data:
  target: zooloaders.autoloader.ZooDataModule
  params:
    data_dir: '../../Datasets/'
    batch_size: 16
    num_workers: 4
    scale: 0.1
    topk: null
    normalize: False
