
model:
  base_learning_rate: 4.5e-6
  target: stage1.models.first_stage_model.VAENoDiscModel
  params:
#    monitor: "val/rec_loss"
    embed_dim: 4 #128 #64
    input_key: 'weight'
    learning_rate: 1.335e-06
#    ckpt_path: 'checkpoints/stage1/norm_base_llama3_3_8b_instruct.pt'
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
#        kl_weight: 5
        kl_weight: 1e-4
#        kl_weight: 0.0001
    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 128
      in_channels: 84
      my_channels: 84
      out_ch: 84
      ch: 128
      ch_mult: [ 1,2, 4]  # num_down = len(ch_mult)-1
      num_res_blocks: 3
      attn_resolutions: [8]
      dropout: 0.0
      in_dim: 16384
      fdim: 16384
#      tanh_out: True