model:
  base_learning_rate: 4.5e-4
  target: stage1.models.first_stage_model.VAENoDiscModel
  params:
    embed_dim: 4
    input_key: 'weight'
    learning_rate: 1.51115e-4
#    ckpt_path: './autocheckpoints/llama_transformer_base_ckpt_block_.pt'
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
#        kl_weight: 0.01
        kl_weight: 0.0001
    ddconfig:
      double_z: True
      tanh_out: False
      z_channels: 4
      resolution: 64
      in_channels: 4
      my_channels: 4
      out_ch: 4
      ch: 128
      ch_mult: [ 1,1, 2, 4]  #num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ 8 ]
      dropout: 0.0
      in_dim: 4096
      fdim: 4096


data:
  target: zooloaders.autoloader.ZooDataModule
  params:
    data_dir: '../../Datasets/'
    batch_size: 16
    num_workers: 4
    scale: 0.1
    topk: null
    normalize: False
