model:
  base_learning_rate: 4.5e-6
  target: stage1.models.simplemodel.VAENoDiscModel
  params:
    embed_dim: 16 #4
    learning_rate: 3.3e-4
    input_key: "weight"
    cond_key: "dataset"
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
        kl_weight: 1e-6
    ddconfig:
      double_z: True
      tanh_out: True
      z_channels: 16
      input_size: 64
      in_channels: 1
      my_channels: 1
      in_dim: 4096
      fdim: 4096