model:
  base_learning_rate: 4.5e-6
  target: stage1.models.simplemodel.VAENoDiscModel
  params:
    embed_dim: 64 #4
    learning_rate: 1.3333e-3
    input_key: "weight"
    cond_key: "dataset"
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
        kl_weight: 1e-4
    ddconfig:
      double_z: True
      z_channels: 64
      input_size: 128
      in_channels: 16
      my_channels: 32
      in_dim: 5923
      fdim: 8192


