model:
  base_learning_rate: 4.5e-6
  target: stage1.models.simplemodel.VAENoDiscModel
  params:
    embed_dim: 16 #4
    learning_rate: 1.113e-3
    input_key: "weight"
    cond_key: "dataset"
    lossconfig:
      target: stage1.modules.losses.CustomLosses.Myloss
      params:
        kl_weight: 1e-6
    ddconfig:
      double_z: True
      z_channels: 16
      input_size: 256
      in_channels: 2
      my_channels: 8
      in_dim: 128256
      fdim: